Nb final edits overall
R4EPI/R4EPIs-website pull request #25
Opened 2019-09-23 23:29 UTC by nsbatra

Went through the whole website and made edits. 

Finally made a RMarkdown script available for download in the case study overview.

Each time I took care to make my changes, save them, use blogdown::build_site() and then use blogdown::serve_site(). Then committing and pushing. 
Despite this, there seemed to be a bunch of extra png images from the place_analyses section - that arise when I build_site(). I think these are somehow remnants of the map for loop at the end (though it has been limited to 20 maps for quite some time). I hope these aren't problematic.

Other random note: In the very first page of the website I noticed the logos kept being off-center despite a lot of Googling and trying to fix it. So I just combined the images into one.

Other random note: As I started making a gif as an overview of the whole template (for the walk-through) I realized that seeing the whole template scroll by before even starting would probably be more intimidating than inspiring, so I cut it. 

Thanks for reviewing!

2019-09-24 14:20 UTC, zkamvar commented
Thanks for the work, Neale! I'm going to go through it, but wanted to make a comment here before I forget.


> Other random note: In the very first page of the website I noticed the logos kept being off-center despite a lot of Googling and trying to fix it. So I just combined the images into one.

That was my fault. I tried to be clever about the alignment, but it turns out aligning images on a webpage is not easy. However, I don't think combining the images works because they are now full of compression artifacts.

2019-09-24 14:27 UTC, zkamvar commented
Not sure where to comment for this, but delete this file: content/welcome/images/RStudio_global_options.jfif

2019-09-25 13:17 UTC, epiamsterdam commented
Hi everyone - this looks really good. I think we will continue to find small errors for fixing, but think the ones below at the moment are the major ones.

* [] Getting started page: insert link in first sentence to the case study
* [] Getting started page: 'Opening templates' section - can we insert link to the case study?
* [] About outbreak templates: the GIF to show how to open the markdown is very small for some reason. On the survey templates page it is much larger - so wonder if it is just a sizing issue?
* [] Credits page - can we please remove the weird sentence about my contribution. Just maybe put Project Lead - Annick Lenglet - and nothing else?
* [] Training materials page: can we change the order to R basics and then the Case study - just to match the order it is on the website
* [] Case study overview: remove the Spina and Lenglet sentence at the bottom of the page
* [] Knitting the report: I think there is a "###Tables" that should appear as a heading, but for whatever reason doesnt appear as a heading

2019-09-26 08:53 UTC, zkamvar requested changes
This is a Herculean effort, Neale. Thank you so much for going through this.

I only had a few nits to pick regarding wording and broken URLs. Regarding the extra images that popped up, I think those might be a result of not naming chunks and adding more in (I didn't look too closely). Essentially, if you have a bunch of unnamed chunks in your RMarkdown file that produce figures it will name them as `unnamed-chunk-<chunk number>-<figure number>.png`. If you then put another chunk in the document, then all other figures for chunks after that one will be renamed/rewritten and some figures would be orphaned. 

Really, that's all the nits I had to pick. I think you've done a wonderful job on the site and the walkthrough. It's very thorough and gives good support for any gotchas that appear :)

2019-09-26 08:53 UTC, zkamvar commented on content/_index.en.md
> +**All coding is open source and freely available and can be used by anyone.** For suggestions
This relates to #18 

```suggestion
**All of the code is open source and freely available and can be used by anyone.** For suggestions 
```

2019-09-26 08:53 UTC, zkamvar commented on content/_index.en.md
> +on what to add or change, please link to our [Github site](https://github.com/R4EPI)
```suggestion
on what to add or change, please [open an issue on GitHub](https://github.com/R4EPI/sitrep/issues).
```

2019-09-26 08:53 UTC, zkamvar commented on content/_index.en.md
> +![Markdowns from R](images/SnipMarkdown.PNG?width=30pc)
"Markdowns" sounds weird to me. It's like calling huckleberries "huckles"

```suggestion
![Available situation report RMarkdown templates](images/SnipMarkdown.PNG?width=30pc)
```

2019-09-26 08:53 UTC, zkamvar commented on content/_index.en.md
> +See [this page](https://r4epis.netlify.com/credits/) for a list of project contibutors.
avoiding "this page" style links

```suggestion
Check out the [list of project contributors](https://r4epis.netlify.com/credits/). 
```

2019-09-26 08:53 UTC, zkamvar commented on content/_index.en.md
> +See these MSF innovation blog posts describing [the origin](https://blogs.msf.org/bloggers/larissa/innovation-introducing-r4epis)
```suggestion
See these MSF innovation blog posts describing [the origin of the R4EPIs project](https://blogs.msf.org/bloggers/larissa/innovation-introducing-r4epis) 
```

2019-09-26 08:53 UTC, zkamvar commented on content/outbreaks/_index.en.md
> +**The outbreak and survey report templates are special R scripts called "R-Markdowns"**, and are included with **sitrep** package installation.
```suggestion
**The outbreak and survey report templates are special "RMarkdown" scripts**, and are included with **sitrep** package installation. 
```

2019-09-26 08:53 UTC, zkamvar commented on content/outbreaks/_index.en.md
> +RMarkdown scripts execute data cleaning and analytical R commands AND are themselves the outline of an automatically-produced report.
```suggestion
RMarkdown scripts give you a way of writing your analysis code and report in one document by allowing you to interleave chunks of code that the computer will run in between explanatory text meant for a person to read.
```

2019-09-26 08:53 UTC, zkamvar commented on content/outbreaks/_index.en.md
> +Situation reports for outbreaks typically focus on describing the data in terms of:
```suggestion
Situation reports for outbreaks typically focus on describing the data in terms of **person**, **time**, and **place**.
```

2019-09-26 08:53 UTC, zkamvar commented on content/outbreaks/_index.en.md
> +* **Person**
```suggestion
```

2019-09-26 08:53 UTC, zkamvar commented on content/outbreaks/_index.en.md
> +* **Time**
```suggestion
```

2019-09-26 08:53 UTC, zkamvar commented on content/outbreaks/_index.en.md
> +* **Place**
```suggestion
```

2019-09-26 08:53 UTC, zkamvar commented on content/outbreaks/_index.en.md
> +
```suggestion
```

2019-09-26 08:53 UTC, zkamvar commented on content/outbreaks/_index.en.md
> +
```suggestion
```

2019-09-26 08:53 UTC, zkamvar commented on content/outbreaks/_index.en.md
> +**Source**: [Chow J, et al. Invasive Meningococcal Meningitis Serogroup C Outbreak in Northwest Nigeria, 2015 – Third Consecutive Outbreak of a New Strain. PLOS Currents Outbreaks. 2016 Jul 7 . Editi
DOIs don't automatically expand to URLs. Normally, I would just put https://doi.org at the beginning of the DOI, but for some reason this DOI is broken.

```suggestion
**Source**: [Chow J, et al. Invasive Meningococcal Meningitis Serogroup C Outbreak in Northwest Nigeria, 2015 – Third Consecutive Outbreak of a New Strain. PLOS Currents Outbreaks. 2016 Jul 7 . Edition 1.](http://currents.plos.org/outbreaks/index.html%3Fp=66532.html)
```

2019-09-26 08:53 UTC, zkamvar commented on content/surveys/_index.en.md
> +The survey report templates are special R scripts called "R-Markdowns", and are included with **sitrep** package installation.
```suggestion
The survey report templates are special "RMarkdown" scripts, and are included with **sitrep** package installation. 
```

2019-09-26 08:53 UTC, zkamvar commented on content/surveys/_index.en.md
> +RMarkdown scripts execute data cleaning and analytical R commands AND are themselves the outline of an automatically-produced report.
```suggestion
RMarkdown scripts give you a way of writing your analysis code and report in one document by allowing you to interleave chunks of code that the computer will run in between explanatory text meant for a person to read.
```

2019-09-26 08:53 UTC, zkamvar commented on content/surveys/_index.en.md
> +* Open Rstudio
```suggestion
* Open RStudio
```

2019-09-26 08:53 UTC, zkamvar commented on content/surveys/_index.en.md
> +![example of opening and saving cholera template](images/opening_template.gif)
Make sure to give the section header room to breathe

```suggestion
![example of opening and saving cholera template](images/opening_template.gif)

```

2019-09-26 08:53 UTC, zkamvar commented on content/surveys/_index.en.md
> +{{% /notice %}}
good catch!

2019-09-26 08:53 UTC, zkamvar commented on content/training/R_Basics/RMarkdown_Orientation.Rmd
> +You can learn more about RMarkdowns [here](https://rmarkdown.rstudio.com/lesson-1.html) and reference this [cheatsheet](/images/rmarkdown_cheatsheet_2.0.pdf)
Why did you add this cheatsheet to our files when it's hosted online?

```suggestion
You can [learn more about RMarkdown here](https://rmarkdown.rstudio.com/lesson-1.html) and reference this [cheatsheet](/images/rmarkdown_cheatsheet_2.0.pdf)  
```

2019-09-26 08:53 UTC, zkamvar commented on content/training/Walk-through/Knitting.Rmd
> +After knitting, you may see warning text in your final report. Typically, it is recommended that you attempt to fix the code that produced the error (see the R Basics - [Errors and Warnings](https://
Do not mix up warning and error. 

```suggestion
After knitting, you may see warning text in your final report. Sometimes these warnings are innocuous (e.g. you tried to filter out a factor level that doesn't exist), but sometimes they are more serious. Typically, it is recommended to read through the warnings and fix them if necessary (see the R Basics - [Errors and Warnings](https://r4epis.netlify.com/training/r_basics/errors_and_warnings/) page.  
```

2019-09-26 08:53 UTC, zkamvar commented on content/training/Walk-through/clean_data.Rmd
> +The commant above successfully converted many of our date variables (remember you can check a variable's class like `class(linelist$date_of_onset`). However, this command did not detect the date vari
```suggestion
The code above successfully converted many of our date variables (remember you can check a variable's class like `class(linelist$date_of_onset`). However, this command did not detect the date variables named with "dt", such as `dtdeath` and `dthospitalization`. We must **add code to convert those variables manually**:  
```

2019-09-26 08:53 UTC, zkamvar commented on content/training/Walk-through/clean_data.Rmd
>  linelist_cleaned$dtdeath <- linelist::guess_dates(linelist_cleaned$dtdeath)
```suggestion
linelist_cleaned$dtdeath <- linelist::guess_dates(linelist_cleaned$dtdeath, error_tolerance = 0.5)
```

2019-09-26 08:53 UTC, zkamvar commented on content/training/Walk-through/clean_data.Rmd
>  linelist_cleaned$dthospitalisation <- linelist::guess_dates(linelist_cleaned$dthospitalisation)
```suggestion
linelist_cleaned$dthospitalisation <- linelist::guess_dates(linelist_cleaned$dthospitalisation, error_tolerance = 0.5)
```

2019-09-26 08:53 UTC, zkamvar commented on content/outbreaks/_index.en.md
>  There is also coding to be able to guide you on conducting simple statistical comparisons between groups (chi square, t-test etc.), as well as the calculation of Odds Ratios (ORs) and Risk Ratios (RR
```suggestion
There is also code to help you conduct simple statistical comparisons between groups (chi square, t-test etc.), as well as the calculation of Odds Ratios (ORs) and Risk Ratios (RR) and running regression models for multivariate analyses.
```

2019-09-26 08:53 UTC, zkamvar commented on content/training/Walk-through/template_setup.Rmd
>  * **stringr** used to clean text/characters
```suggestion
* **stringr** used to clean and handle text/characters (known in computer science as "strings")
```

2019-09-26 08:53 UTC, zkamvar commented on content/training/Walk-through/template_setup.Rmd
> +**Lastly, the labels that will be used in epidemic curve plots are defined**. These should not need any adjustment. You may notice that the subtitle label uses the special term `%s` as a placeholder
d'oh! That was something I should have changed!

```suggestion
**Lastly, the labels that will be used in epidemic curve plots are defined**. These should not need any adjustment. You may notice that the subtitle label uses `reporting_week` in curly braces---this means that the value of `reporting_week` defined in the previous chunk will show in its place.  
```

The epicurve labels for the templates should be generated sing `str_glue` from stringr like this:

```r
subtitle = str_glue("Source: MSF data from {reporting_week}")
```

2019-09-26 08:53 UTC, zkamvar commented on content/welcome/_index.en.md
> +> **Caveat if using MRAN**: MRAN is a version of R that has modifications that are outside the scope of this project, however, it should be noted that it also locks the version of all packages to a s
I've migrated the wiki on the github to this website so there is no need to link there. 

```suggestion
{{% notice info %}}
**Caveat if using MRAN**: MRAN is a version of R that has modifications that are outside the scope of this project, however, it should be noted that it also locks the version of all packages to a specific date, so care is needed to specify repositories when installing R packages. If you are unsure whether you have MRAN or CRAN R installed then see this [FAQ](https://r4epis.netlify.com/faq/#i-am-unsure-if-i-have-the-mran-or-cran-version-of-r-installed). 
{{% /notice %}}
```

2019-09-26 08:53 UTC, zkamvar commented on content/welcome/_index.en.md
> +![RStudio global options window showing a setting optimal for reproducibility](images/RStudio_global_options.jfif?width=30pc)
You might want to change this file name. jfif is not a commonly recognized format.

2019-09-26 08:53 UTC, zkamvar commented on content/welcome/_index.en.md
> +If you are unsure whether you have MRAN or CRAN R installed then see the [FAQ](<https://github.com/R4EPI/sitrep/wiki/4).
```suggestion
If you are unsure whether you have MRAN or CRAN R installed then see this [FAQ](https://r4epis.netlify.com/faq/#i-am-unsure-if-i-have-the-mran-or-cran-version-of-r-installed).
```

2019-09-26 08:53 UTC, zkamvar commented on content/welcome/_index.en.md
> +If you are getting errors, check the [FAQ section](<https://github.com/R4EPI/sitrep/wiki/4) of the **sitrep** wiki.
```suggestion
If you are getting errors, check the [frequently asked questions](https://r4epis.netlify.com/faq/).
```

2019-09-26 19:19 UTC, nsbatra commented on content/training/R_Basics/RMarkdown_Orientation.Rmd
> +You can learn more about RMarkdowns [here](https://rmarkdown.rstudio.com/lesson-1.html) and reference this [cheatsheet](/images/rmarkdown_cheatsheet_2.0.pdf)
I just figured it was safer to have stored vs. linked in case the link changes someday. But this is fine too.

2019-09-26 19:56 UTC, nsbatra commented
> Really, that's all the nits I had to pick. I think you've done a wonderful job on the site and the walkthrough. It's very thorough and gives good support for any gotchas that appear :)

Thank you Zhian :-)

2019-09-27 08:39 UTC, zkamvar commented on content/_index.en.md
> +**All coding is open source and freely available and can be used by anyone.** For suggestions
Did you not like this suggestion?

2019-09-27 09:16 UTC, zkamvar approved these changes

2019-09-27 09:17 UTC, merged